title: deadpine.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Designer working at the intersection of product design and brand identity
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deadpine.xyz/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: deadpine_xyz
github_username: deadpine
permalink: pretty


markdown: kramdown
plugins:
  - jekyll-feed
